repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        types: [python]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        types: [python]

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.7.1
    hooks:
      - id: rst-backticks
      - id: rst-inline-touching-normal

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.6.0
    hooks:
      - id: pylint
