version: '3.3'  
services:
  app:
    image: best11fantasycricket:latest
    ports:
      - "8080:80"
    environment:
      - MAX_WORKERS=1
      - LOG_LEVEL=DEBUG
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 100M