FROM python:3.8-slim as build

WORKDIR /

COPY ./requirements.txt ./requirements.txt
RUN apt-get update && \
    apt-get -y install gcc mono-mcs && \
    rm -rf /var/lib/apt/lists/*
RUN pip install -r requirements.txt

COPY ./app /app
COPY ./crawler /crawler
COPY ./scrapy.cfg /scrapy.cfg

ENTRYPOINT ["uvicorn", "app.main:app"]
