version: 2.1

orbs:
  python: circleci/python@1.3.2
  docker: circleci/docker@1.5.0

jobs:
  build-and-test:
    executor: python/default
    environment:
      TEST: True
    steps:
      - checkout
      - setup_remote_docker
      - docker/install-docker-compose
      - run:
          command: |
            python -m pip install --upgrade pip
            pip install pylint
            pip install -r requirements.txt
            pip install scrapy-autounit
          name: Install dependencies
      - run:
          command: |
            scrapy crawl espn-live
            scrapy crawl espn-players
            python3 -m unittest discover autounit/tests/
          name: Crawler Test with autounit
      - run:
          command: |
            pylint app -E
            pylint app --exit-zero
          name: Lint with pylint
      - run:
          name: Test with pytest
          command: |
            docker -v
            docker-compose -v
            docker-compose -f docker/docker-compose-test.yaml up --build --exit-code-from test
workflows:
  main:
    jobs:
      - build-and-test
